apiVersion: apps/v1
kind: Deployment
metadata:
  name: testapp-nodeport
  labels:
    app: testapp    
spec:
  replicas: 4
  selector:
    matchLabels:
      app: testapp
  template:
    metadata:
      labels:
        app: testapp
    spec:
      containers:
      - image: kiran2361993/kubegame:v1
        name: kubegame
        ports:
         - containerPort: 80
